import typescript from '@rollup/plugin-typescript';
import { defineConfig } from 'rollup';
import fs from 'fs';

const pkg = JSON.parse(fs.readFileSync('./package.json'));
const version = process.env.SEMANTIC_RELEASE_NEXT_VERSION || pkg.version;

console.log('building version:', version);

const banner = `/**
 * lg-solution-formatter v${version} - a luogu solution formatter
 * Copyright (c) 2023-${new Date().getFullYear()}, Imken Luo <me@imken.moe> (MIT Licensed)
 * https://github.com/immccn123/lg-solution-formatter
 * 
 * based on marked
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./src/
 */
`;

export default defineConfig([
  {
    input: 'src/formatter.ts',
    output: [{
      file: 'lib/lg-solution-formatter.esm.js',
      format: 'esm',
      sourcemap: true,
      banner
    },
    {
      file: 'lib/lg-solution-formatter.umd.js',
      format: 'umd',
      name: 'lg-solution-formatter',
      sourcemap: true,
      banner
    },
    {
      file: 'lib/lg-solution-formatter.cjs',
      format: 'cjs',
      name: 'lg-solution-formatter',
      sourcemap: true,
      banner
    }],
    plugins: [
      typescript()
    ]
  }
]);
